### PR TITLE
Form feature

### PR DESCRIPTION
**Pull request by abeidahmed**
- Create, edit users
- Show list of users on the home page
- Show single user on the show page

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @abeidahmed and @menyagah  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the project's minimal requirements carefully and great on the `has_secure_password`, and the `normalize_fields` methods you added, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] In resources, allow [:new, :create, :edit, :update] only, remove the show [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route1.png), [screenshot 2](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route2.png)
- [x] The create action should redirect_to new_user_path if user was saved ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_create.png) from Odin)
- [x] YOu should have a raw html form commented out and a rails form_tag helper commented out for the new user and edit user, please add them as the project specifications say
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, great job you've done so far in this project and in the past required changes. However, there is still one small thing you should make before moving on!

- [x] As long as you don't use the index resource in your routes file, so it doesn't make sense to use it in the users controller, and in the index.html.erb file as well (you don't need those). Kindly remove them and submit for another review 🙏🙏

<hr>

Good luck and happy coding ✔👨‍💻💻

**Comment by abeidahmed** [comment]
> # **Changes Required stop_signrecycle**
> Hello there, great job you've done so far in this project and in the past required changes. However, there is still one small thing you should make before moving on!
> 
> * [x]  As long as you don't use the index resource in your routes file, so it doesn't make sense to use it in the users controller, and in the index.html.erb file as well (you don't need those). Kindly remove them and submit for another review praypray
> 
> Good luck and happy coding

I am using it to render the root page bro.

**Review by LamiaSristy — APPROVED** [review]
# Status: Approved. 💯 🥇 🎉 🎉

Hello Team!!!

# Don't make any changes after asking a CRR.

Your project is now approved. Congratulations on your hard work. 🛠️ 


You can merge the branch now, good luck with your next Project 🚀.

Feel free to reach me at @lamiasristy 🙋

**Pull request merged**
